spring:
  application:
    name: favourite-recipes-server
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    password: postgres
    schemas: public
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.flywaydb: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE


#  flyway:
#    enabled: true
#    locations: classpath:db/migration


