server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: favourite-recipes-server
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${DATASOURCE_URL}
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    schemas: public

api:
  server:
    url: http://localhost:8080/prod
